### ISSUE TITLE
Dependabot offers updates incompatible with deptree

### ISSUE THREAD

**Issue by kojiromike** [dependabot/feedback#581] opened 2019-07-19 13:24 UTC
We use Python/Pipfile. One of our dependencies is signxml. Its dependency graph looks like this right now:

```
$ pipenv graph
signxml==2.6.0
  - asn1crypto [required: >=0.24.0, installed: 0.24.0]
  - certifi [required: >=2018.1.18, installed: 2019.6.16]
  - cryptography [required: >=2.1.4,<3, installed: 2.7]
    - asn1crypto [required: >=0.21.0, installed: 0.24.0]
    - cffi [required: >=1.8,!=1.11.3, installed: 1.12.3]
      - pycparser [required: Any, installed: 2.19]
    - six [required: >=1.4.1, installed: 1.12.0]
  - defusedxml [required: >=0.5.0,<1, installed: 0.6.0]
  - eight [required: >=0.4.2,<1, installed: 0.4.2]
    - future [required: >=0.16,<0.17, installed: 0.16.0]
  - lxml [required: >=4.2.1,<5, installed: 4.3.4]
  - pyOpenSSL [required: >=17.5.0,<19, installed: 18.0.0]
    - cryptography [required: >=2.2.1, installed: 2.7]
      - asn1crypto [required: >=0.21.0, installed: 0.24.0]
      - cffi [required: >=1.8,!=1.11.3, installed: 1.12.3]
        - pycparser [required: Any, installed: 2.19]
      - six [required: >=1.4.1, installed: 1.12.0]
    - six [required: >=1.5.2, installed: 1.12.0]
```

Every time we do update our dependencies, dependabot creates a new PR to update to future==0.17.1. But that is not a valid resolution of the dependency graph.

**Comment by greysteil** [comment] 2019-07-21 20:35
Thanks for the bug report @kojiromike. It's very hard to debug this one, however - Dependabot shells out to Pipenv so it's likely that the bug originates there, but without a repo that we can reproduce on it will be hard to report to them. I presume the repo in question is private?

**Comment by kojiromike** [comment] 2019-07-22 13:17
Yes. We are paying GitHub customers, though, so I can try to find out if we are covered under some kind of NDA.

**Comment by kojiromike** [comment] 2019-07-24 15:43
I sent an email to support@dependabot.com with further details.

**Comment by greysteil** [comment] 2019-07-25 13:33
Just took a look into this. Dependabot doesn't realise that your `requirement.txt` and `Pipfile` are connected because you don't have a `Pipfile.lock` committed. If you commit that, it should figure it out and not create incompatible updates.

**Comment by greysteil** [comment] 2019-07-25 13:33
Can you try the above and close this if it works?

**Comment by kojiromike** [comment] 2019-07-25 13:48
Ah... unfortunately I can't. Our team decided not to commit the Pipfile.lock because we have people using different environments (macOS and Linux, for two), based on the unclear conversation in pypa/pipenv#598.

At least, I will need to figure out how to make a guaranteed-consistent lockfile before I can do that, and I'm not sure when I'll be able to work on that.

**Comment by greysteil** [comment] 2019-07-25 16:00
Ah, that's too bad. The work required fo Dependabot to recognise those requirement.txt files as outputs of Pipenv is just too much - I can see you're using a custom wrapper script to build them, and there's just no way Dependabot can support that I'm afraid.

**Closed** 2019-10-23 09:57 UTC
Labels: wontfix
