### ISSUE TITLE
dependabot trying to downgrade gemspec dependency

### ISSUE THREAD

**Issue by JacobEvelyn** [dependabot/feedback#126] opened 2018-04-11 11:30 UTC
Hi there. Looks like I've got a similar issue to #122 but for a Ruby gem—see [this dependabot PR](https://github.com/JacobEvelyn/friends/pull/195/files). Let me know what I can do to help!

**Comment by greysteil** [comment] 2018-04-11 11:31
Uh oh, I'll take a look. Since the repo's open source it should be really easy for me to replicate, but I'll let you know if I have any trouble.

Thanks for reporting, and for giving Dependabot a try.

**Comment by JacobEvelyn** [comment] 2018-04-11 12:03
Thanks!

**Comment by greysteil** [comment] 2018-04-11 13:00
Should be fixed by https://github.com/dependabot/dependabot-core/commit/8ee9aae4e9dd03d8216899846030d7494ee7e752, which is deploying now.

**Comment by greysteil** [comment] 2018-04-11 13:11
Fix confirmed. Sorry about that, and thanks for adding Dependabot to friends. I remember reading about it on HackerNews month ago - great project!

**Closed by greysteil** 2018-04-11 13:11 UTC

**Comment by JacobEvelyn** [comment] 2018-04-11 16:45
Thanks, I appreciate it @greysteil!
