### ISSUE TITLE
PR should reliably link to readme and/or to version diff on github

### ISSUE THREAD

**Issue by czj** [dependabot/feedback#31] opened 2017-10-25 07:47 UTC
We where using Deppbot for about a year and switched to Dependabot because it is more complete & polished, but we miss a single key feature from Deppbot: direct link to the Ruby gem's README file and/or a diff of commits between the two versions on Github. It allows us to accept an upgrade and see what's changed.

Dependabot seemed to have this feature. For rake It worked, for instance:

![image](https://i.imgur.com/IvNm4gM.png)

But on some other PR (private projects) we get nothing:

![image](https://i.imgur.com/hdG09bR.png)

Are you working on improving this feature ?

Thanks :)

**Comment by greysteil** [comment] 2017-10-25 07:55
We're always trying to improve how good Dependabot is at finding the source code for dependencies it updates. If you comment below with the name of a dependency that we miss I'll dig into it each time and try to fix it.

(Sometimes this requires getting a PR accepted by the dependency author to add links to the source code in their registry listing. I've only ever had a good experience doing that, so very happy to take that on, too.)

**Comment by isc** [comment] 2017-10-25 08:13
Hi,

There is a miss on `mocha`, they do have a RELEASE.md file on the repository (https://github.com/freerange/mocha) which is linked on rubygems (although it is not in the gemspec).

**Comment by greysteil** [comment] 2017-10-25 08:14
Hmm, we shouldn't be missing that. What's the name of the repo we missed it on? I want to take a quick look at the Gemfile to see if Dependabot is mistaking your source for a private one.

**Comment by isc** [comment] 2017-10-25 08:46
It's a private repository ; isc/adminium.

**Comment by greysteil** [comment] 2017-10-25 09:22
@czj @isc thanks for the above. Looks like there were two separate issues, both now fixed:
1) Dependabot thought all Gemfile declarations that were wrapped in a `source` block were from private repos, so wasn't looking on Rubygems for details of them. That explains why it won't have been linking to changelogs etc. for your repos, @czj. You should now see the same kind of links you saw on `rake` this morning on pretty much all the PRs Dependabot creates for you.
2) Dependabot wasn't looking for changelogs named `release.md`, so didn't pick up that mocha changelog. That's now fixed.

Both fixes are in the latest release of [Dependabot Core](https://github.com/dependabot/dependabot-core/blob/master/CHANGELOG.md), which all future PRs will use. (Unfortunately, asking Dependabot to rebase existing PRs **won't** update the PR descriptions.)

I'm going to close this issue, but if you see any other PRs where you think we should have been able to find links, add an @dependabot comment on them and I'll take a look.

**Closed by greysteil** 2017-10-25 09:22 UTC

**Comment by isc** [comment] 2017-10-27 12:23
Thanks a lot for the quick update.
I have a new dependency without any link ; unicorn on isc/dbinsights.
It clearly isn't standard compared to other gems. The right info can be found at https://bogomips.org/unicorn/NEWS.html, I don't know if you have some kind of hardcoded links dictionary. Maybe if a standard Changelog cannot be found, you could still link to the homepage specified in the gemspec.

**Comment by greysteil** [comment] 2017-10-27 13:46
That’s a really good idea on linking to the homepage - I’ll make it so.

On hard coded change log links - we don’t have a setup for those, and I think encouraging authors to put it in their gem metadata is a better solution, but we could make that clearer. I’ll see what I can do there.

**Comment by isc** [comment] 2017-10-30 08:23
Hi,
Another unlinked dependency ; rack-mini-profiler for isc/adminium. There is a `CHANGELOG.md` file in the Gem repository, but I guess the problem is the github repo is not referenced in the gemspec file.

**Comment by greysteil** [comment] 2017-10-30 08:48
Will be fixed by https://github.com/MiniProfiler/rack-mini-profiler/pull/318.
