### ISSUE TITLE
Check fails for Elixir umbrella project

### ISSUE THREAD

**Issue by kevinbader** [dependabot/feedback#280] opened 2018-11-26 11:49 UTC
Hi,

I get the following error when checking my [Elixir umbrella project](/Accenture/reactive-interaction-gateway):

```elixir
** (Code.LoadError) could not load /home/dependabot/dependabot-updater/dependabot_tmp_dir/version
    (elixir) lib/code.ex:1147: Code.find_file/2
    (elixir) lib/code.ex:706: Code.eval_file/2
    mix.exs:29: Rig.Umbrella.Mixfile.versions/0
    mix.exs:6: Rig.Umbrella.Mixfile.project/0
    (mix) lib/mix/project.ex:685: Mix.Project.get_project_config/1
    (mix) lib/mix/project.ex:110: Mix.Project.push/3
{"error":""}
```

Is this an issue with the project's mix file?

**Comment by greysteil** [comment] 2018-11-26 11:50
Looks more likely to be a problem with Dependabot's sanitization processes. Let me take a look.

**Comment by greysteil** [comment] 2018-11-26 12:05
OK, this is definitely caused by the `Code.eval_file` pattern used in the project's mix file. Dependabot isn't fetching that file (it only fetches dependency files, rather than cloning the repo) so is then unable to evaluate the mix file.

I haven't seen the `Code.eval_file` pattern used in a mix file before. Dependabot has some sanitization to handle `File.read` calls, but it's going to be harder for me to sanitize `Code.eval_file` (because it's less obvious what a replacement value should be). Are you committed to using that pattern, and is it a common one?

**Comment by greysteil** [comment] 2018-11-26 12:50
FYI, I've just pushed that change. I'll re-run Dependabot on your repo as soon as it's deployed (in about 10 minutes time), and close this assuming everything runs as expected.

**Comment by greysteil** [comment] 2018-11-26 13:45
Looks like this is now working. Thanks for the report! https://github.com/kevinbader/reactive-interaction-gateway/pulls

**Comment by kevinbader** [comment] 2018-11-26 13:46
Thanks a lot!

**Closed by greysteil** 2018-11-26 13:45 UTC

**Comment by bdubaut** [comment] 2019-05-12 06:40
@greysteil Hi, I seem to have the same problem on my umbrella project.
```
** (Code.LoadError) could not load /home/dependabot/dependabot-updater/config/config.exs
    (elixir) lib/code.ex:1147: Code.find_file/2
    (elixir) lib/code.ex:706: Code.eval_file/2
    (mix) lib/mix/config.ex:220: Mix.Config.eval!/2
    (mix) lib/mix/tasks/loadconfig.ex:38: Mix.Tasks.Loadconfig.load/1
    (mix) lib/mix/tasks/loadconfig.ex:28: Mix.Tasks.Loadconfig.run/1
    (mix) lib/mix/task.ex:331: Mix.Task.run_task/3
    (mix) lib/mix/cli.ex:78: Mix.CLI.run_task/2

{"error":""}
```

**Comment by greysteil** [comment] 2019-05-12 12:23
Thanks for this. The fix is https://github.com/dependabot/dependabot-core/commit/ea4fd130ce7ae88e5a36be9f6217f51cd94bfa04, which I'm deploying now.

(One housekeeping point: for future issues, it would be great if you could open a new issue rather than commenting on an old ones. In most cases the issue is new, rather than a regression, as we keep a big test suite on Dependabot Core for fixes like this.)

**Comment by bdubaut** [comment] 2019-05-12 14:37
> it would be great if you could open a new issue rather than commenting on an old ones. In most cases the issue is new, rather than a regression, as we keep a big test suite on Dependabot Core for fixes like this.

I will keep that in mind! Thanks a lot
