### ISSUE TITLE
npm 'optional' fights

### ISSUE THREAD

**Issue by Floppy** [dependabot/feedback#197] opened 2018-09-27 08:04 UTC
I've noticed that we get a lot of change in our `package-lock.json` files around `optional` settings for various packages (see https://github.com/apolitical/styleguide/pull/122/files for an example). 

I think it's caused by https://github.com/npm/npm/issues/17722, which is that the file will be different if it's generated on MacOS or Linux, because of system dependencies of those packages.

We're a mixed-OS development team anyway, so we need to solve this for ourselves, but I wondered if you had any thought on somehow making Dependabot somehow ignore or respect the setting that's already in there.

/cc @huwd @gisleburt @thethomaseffect

**Comment by greysteil** [comment] 2018-10-02 18:31
Sorry for the slow reply on this one from me - I've been a bit rushed for the last couple of days.

This one is tricky. There might be something that Dependabot can do in post-processing lockfiles to avoid the npm bug, but it's dangerous for us to meddle with the lockfile too much (in case we introduce our own bugs).

I'm guessing there's a reason you're sticking to `npm`, rather than `yarn`?

**Comment by Floppy** [comment] 2018-10-05 13:19
Same, we've not needed to change yet, but perhaps it's sensible to do so.

**Comment by feelepxyz** [comment] 2018-10-29 16:40
@Floppy @prymitive just confirmed that this issue has been fixed in this pr: https://github.com/npm/cli/pull/76
Discussed here: https://npm.community/t/package-lock-json-is-not-complete-on-first-run-for-some-modules/1817

If I understand this issue correctly, once this lands in npm `optional: true` will be added to all sub-dependencies that have an optional parent, currently it will only be set to optional if the parent is optional on the platform `npm install` runs on.

**Comment by Floppy** [comment] 2018-10-30 12:08
@feelepxyz superb! Thanks for the update :)

**Comment by feelepxyz** [comment] 2019-01-22 13:37
This should now be fixed in `npm@6.6.0` 🎉

You'll need to install the new version of npm to get consistent results from running npm install: `npm install -g npm@6.6.0`

The fix in npm: https://github.com/npm/cli/commit/134207174652e1eb6d7b0f44fd9858a0b6a0cd6c

**Closed by feelepxyz** 2019-01-22 13:37 UTC

**Comment by roopakv** [comment] 2020-01-20 19:02
We are recently seeing this issue, specifically when updating `@storybook/react`. 

my local (mac) and my CI (linux) both are consistent, however dependabot is not. the diff i am seeing that dependabot is not adding id below

![image](https://user-images.githubusercontent.com/678239/72751357-477f6d80-3b74-11ea-8b7b-115c7aea0fe6.png)

**Comment by feelepxyz** [comment] 2020-01-21 09:36
@roopakv this is usually because of differing npm versions and should be fixed in the latest version, which version are you running locally and on ci? To install the latest version: `npm install -g npm@latest`

**Comment by roopakv** [comment] 2020-01-21 13:34
Yeah I thought that was the case and it seems like we are running the same certain Everette l everywhere.

**Comment by roopakv** [comment] 2020-01-27 19:58
@feelepxyz any update here. We are seeing this happen more frequently now.

**Comment by feelepxyz** [comment] 2020-01-28 13:58
@roopakv what version of `npm` are you running? I'm pretty sure it's caused by a version discrepancy as we worked on the patch in npm that fixed this problem by making it deterministic.

**Comment by roopakv** [comment] 2020-01-28 14:26
We use npm 6.13.6 everywhere.
