### ISSUE TITLE
Include *all* hashes for a project Python project

### ISSUE THREAD

**Issue by dstufft** [dependabot/feedback#235] opened 2018-10-26 04:08 UTC
It appears you're using pip-compile here, which is great... but it has one sort of less than ideal behavior. Whenever you're pinning hashes (like pypa/warehouse is doing) it will only include the hashes for files that match the current target environment. What would be great is if instead dependabot included *all* available hashes in the PR.

There is a Python library/tool that implements this called [hashin](https://pypi.org/project/hashin/) that might be useful here. The biggest downside is that it takes as an input the name of the package to update the hash of, so you'd have to parse the requirements.txt file to determine what to pass into hashin.

One potential wrinkle here, is that people can upload additional files after the fact and it would be great if dependabot made sure to update the PR to include additional files that got uploaded after the PR was created.

**Comment by greysteil** [comment] 2018-10-28 10:32
Interesting, thanks for the heads up @dstufft.

I've just taken a look through how pip-tools [generates its hashes](https://github.com/jazzband/pip-tools/blob/master/piptools/repositories/pypi.py#L230-L255) and I can't find that filter - any idea of a package I can use to reproduce the behaviour? Once I've got that I can set Dependabot to pull in additional hashes from hashin.

On generating additional files, that sounds like a tricky one. On the plus side, since Dependabot is shelling out to pip-tools for each update if it ever happens then the additional hashes will be included in whatever PR Dependabot opens next (for any unrelated dependency).

**Comment by dstufft** [comment] 2018-10-28 18:34
The filter is in the ``PackageFinder`` class, which will ignore files that don't match the current environment. One example of this is docutils, which has 3 files:

- a ``.tar.gz`` that will show up on all environments.
- a ``py3`` wheel that will only show up when run under Python 3.
- a ``py2`` wheel that will only show up when run under Python 2.

Also pretty much any project that ships compiled wheels will exhibit this behavior as well, like the ``cryptography`` project, which has some wheels that are only for Windows, some only for Linux, some only for macOS, etc.

**Comment by dstufft** [comment] 2018-10-28 18:37
Just as an FYI, the biggest issue with not updating if additional files are uploaded, is that it can cause spurious errors. This is sort of a pip bug though.

Basically, pip works by selecting the file it wants to install, then comparing that against the list of hashes present in the file. If it doesn't match any of them, it errors out. The problem comes if someone uploads a file that pip prefers, say 2 days later, then pip will start trying to use that file... and then will error out because that file's hash doesn't exist. There's an open issue on pip to make it smarter so that it will choose a file it has hashes for, over one it doesn't instead of erroring in this case, but currently it can create a poor UX.

**Comment by greysteil** [comment] 2019-01-01 19:17
Fixed in https://github.com/dependabot/dependabot-core/commit/15c08c7f4c2b3dc7a32ed54bbf57a7edfac993ec. Dependabot will now look for all hashes when it updates a dependency, if all hashes were included in the compiled `requirements.txt` file previously. Apologies for the delay getting to this one!

**Closed by greysteil** 2019-01-01 19:17 UTC
