### ISSUE TITLE
Option to have a PR combining all version updates

### ISSUE THREAD

**Issue by josesimoes** [dependabot/feedback#180] opened 2018-09-12 13:33 UTC
It looks like that dependabot submits a PR for each package that has it's version updated, instead of a single one.

This is far less than ideal in particular when the update triggers a new version on the package build from the PRs being merged. If there are three dependent packages updates, that would bump the component version by 3, when all that could (should?) be a single version bump.

**Comment by greysteil** [comment] 2018-09-12 14:37
This is a dupe of https://github.com/dependabot/feedback/issues/5, which is a feature I'd (still) love to add!

**Closed by greysteil** 2018-09-12 14:37 UTC
