### ISSUE TITLE
Dependabot often forgets to merge the PR when the check passes

### ISSUE THREAD

**Issue by JustArchi** [dependabot/feedback#452] opened 2019-04-26 14:25 UTC
Hello.

It's very often scenario for me that dependabot sadly doesn't automatically merge PRs when the status checks pass. I have configured the CI in my repos with appropriate `Required` tags from GitHub, so dependabot is able to immediately tell which status checks need to pass, if needed.

Usually, dependabot simply forgets to do its thing right, but wakes up when triggered by `merge` command, like **[here](https://github.com/JustArchiNET/ArchiSteamFarm/pull/1209)**.

> If all status checks pass Dependabot will automatically merge this pull request. [2 days ago]
> (...)
> dependabot-bot merge [5 hours ago]
> dependabot-bot merged commit 15eb5ab into master 5 hours ago

Sometimes, the bot doesn't even react to commands, as if everything suddenly died. The PR needs to be fixed/merged manually, like **[here](https://github.com/JustArchiNET/ASF-WebConfigGenerator/pull/91)**.

> If all status checks pass Dependabot will automatically merge this pull request.
> (...)
> dependabot-bot wake up, this PR is 15 days old already 😕

The issue is totally random, sometimes (but very rarely), dependabot will magically wake up itself and merge the PRs several hours after the checks have passed, and this is a good thing, brief network/rate-limiting issues are to be expected and I do not require auto-merge right after the last CI check passes, but leaving PRs abandoned in a limbo and requiring from developers to issue commands when dependabot states itself that it'll merge the PR automatically is... disappointing. I'd be fine waiting even for the next day if needed, but this issue usually lasts infinitely, until the command triggers it or dev merges manually.

I'm not entirely sure what the root cause of this is, but if by any chance I'm alone with this issue then just set up some kind of watches for my `JustArchiNET` repos and wait for that to happen. Last accident is from today. This happens with both live updates (npm/nuget) and daily updates (git submodules).

Thank you in advance for taking a look.

**Comment by greysteil** [comment] 2019-06-14 09:18
This *should* be fixed now. It was caused by an issue with Dependabot listening for check suite statuses, rather than check run statuses. I'm going to close this, but if Dependabot fails to automerge when it should do for you please don't hesitate to get in touch.

We also have a daily catchup job that loops through unmerged PRs that should be automergable in order to catch any that are missed (due to a missed webhook or something like that).

**Closed by greysteil** 2019-06-14 09:18 UTC
