### ISSUE TITLE
Live updates sometimes don't pick up new gems?

### ISSUE THREAD

**Issue by rdunlop** [dependabot/feedback#471] opened 2019-05-20 20:32 UTC
the rubygems package `ffi` version 1.11.0 got yanked today, and 1.11.1 has been released.

https://rubygems.org/gems/ffi/versions

I know this because some of my builds are failing.

Strangely, my project (tablexi/badges) is set for "Live" updates...but doesn't have a new PR open to update from 1.11.0 to 1.11.1? Why not?

**Comment by greysteil** [comment] 2019-05-20 20:48
Good question. Come to think of it, I missed some Rubygems updates today. Let me take a look. We haven’t changed our webhook logic...

**Comment by greysteil** [comment] 2019-05-20 23:19
FYI, I've added some logging on our side to determine whether Rubygems has stopped sending webhooks. I have a suspicion that that is the issue.

**Comment by connorshea** [comment] 2019-05-21 01:46
I was going to open an issue about dependabot giving me ffi 1.11.0, which caused problems when it was yanked, but it looks like this issue already covers it.

Should Dependabot run an 'emergency' update across all repositories when a gem is yanked like this, in the same way it does for major security updates?

**Comment by greysteil** [comment] 2019-05-21 09:37
Have confirmed that Rubygems aren't sending webhooks for gem pushes. Looks like the culprit is [here](https://github.com/rubygems/rubygems.org/commit/ec1b2b100e850107b740c435fae52edd5b94cc2c#r33616117).

On handling yanked versions more generally - do one of you want to open a separate issue? Dependabot's current logic (brand new as of this morning) is to ask all PRs updating to a yanked version to rebase, which will cause them to close. We could do more here, though - I like your idea @connorshea, and we should probably comment on merged PRs, too (at the very least).

**Closed** 2019-05-21 09:38 UTC

**Comment by greysteil** [comment] 2019-05-21 14:13
Now fixed in Rubygems 🎉

**Comment by rdunlop** [comment] 2019-05-21 14:32
Thanks @greysteil
