### ISSUE TITLE
PR closed when it shouldn't have been?

### ISSUE THREAD

**Issue by RohanNagar** [dependabot/feedback#116] opened 2018-04-02 17:09 UTC
Hello,

I was going through Dependabot's PRs this morning and something weird happened. The first PR I merged was RohanNagar/thunder#114, which updated a bunch of dependencies that share the same version number.

Once I merged that, I looked at RohanNagar/thunder#116 and found that Dependabot closed this without rebasing, saying "Looks like these dependencies are updatable in another way, so this is no longer needed.". However, the dependencies in that PR were not updated by the one that was merged or by any other commit.

Is this a bug? (Language is Java)

**Comment by greysteil** [comment] 2018-04-02 17:12
Hmmm, this does look like a bug. I'll look into it - thanks for reporting.

**Comment by RohanNagar** [comment] 2018-04-09 16:54
Bug was reproduced this morning: I just merged RohanNagar/thunder#125, and dependabot closed RohanNagar/thunder#124 with the same message, though those dependencies have not been updated on the master branch yet.

**Comment by greysteil** [comment] 2018-04-10 17:54
Thanks Rohan. I've just figured out what this is - it's a backend change we made a couple of weeks ago that is causing some randomness on our side (the source of the problem is the ordering of dependencies in multi-dependency PRs).

The fix is a little complex and I'm pressed for time this evening, but I'll have a fix shipped tomorrow at the latest.

Thanks masses for reporting!

**Comment by greysteil** [comment] 2018-04-11 09:43
This should be fixed now - let me know if you see it again. 🎉

**Closed by greysteil** 2018-04-11 09:43 UTC

**Comment by RohanNagar** [comment] 2018-04-11 14:09
Thanks @greysteil!
