### ISSUE TITLE
Configurable branch name, commit message

### ISSUE THREAD

**Issue by dmsergeevN26** [dependabot/feedback#510] opened 2019-06-07 09:15 UTC
Hello,

Are there any plans to add customization of the branch name and the commit message? Preferably from a config file on a repository basis? This is a blocker for Dependabot adoption for us.

Thank you

**Comment by greysteil** [comment] 2019-06-07 09:57
Looks like you also commented on https://github.com/dependabot/feedback/issues/443, which I've just responded to - is this a duplicate of that?

**Comment by dmsergeevN26** [comment] 2019-06-07 10:02
Yes, created for better visibility :) Thank you.

**Comment by greysteil** [comment] 2019-06-25 12:29
I'm going to close this as a duplicate and continue the conversation in #443.

**Closed by greysteil** 2019-06-25 12:29 UTC
