### ISSUE TITLE
Elixir: consider running `mix deps.unlock --unused` when bumping

### ISSUE THREAD

**Issue by doughsay** [dependabot/feedback#45] opened 2018-06-10 20:52 UTC
When bumping a dependency that changes sub-dependencies, the sub dependencies will linger in your `mix.lock` unless you run `mix deps.unlock --unused`.

Here's an example: https://github.com/peek-travel/tipalti-elixir/pull/13

excoveralls from 0.8.2 to 0.9.0 swapped out their use of `jsx` with `jason`.  `jsx` is now no longer a transitive dependency of my project, but it's going to remain in the lock file until someone manually runs the unlock command.

Not a huge deal by any means, but I like to keep things tidy.  Is there any downside to just always running this command after a bump?

**Comment by doughsay** [comment] 2018-06-10 20:57
(note that I checkout out the PR branch, manually ran the command and updated the PR after I opened this issue)

**Comment by greysteil** [comment] 2018-06-10 20:59
Great shout - we should do this. Fancy taking a look at the Elixir code [here](https://github.com/dependabot/dependabot-core/blob/master/helpers/elixir/bin/do_update.exs) to make that change? I can do it, but contributions are always welcome 🙂.

**Comment by greysteil** [comment] 2018-06-10 22:53
Relevant `mix` code is at https://github.com/elixir-lang/elixir/blob/master/lib/mix/lib/mix/tasks/deps.unlock.ex

**Comment by greysteil** [comment] 2018-06-11 09:42
Fixed in https://github.com/dependabot/dependabot-core/commit/90e62bf7b6eba0260591bae7e725d06c88c2cf74

**Closed by greysteil** 2018-06-11 09:42 UTC

**Comment by greysteil** [comment] 2018-06-11 13:51
Update: I've had to revert that commit as it was causing some errors. I'll dig into them and try to figure out the cause.
